---
output:
  pdf_document: default
  html_document: default
classoption: landscape
geometry: margin=0.5cm
---

```{r setup2, include=FALSE}
library(data.table)
library(sandwich)
library(lmtest)
library(stargazer)
library(ggplot2)
library(patchwork)
library(foreign)
library(kableExtra)

# load data & get records with quotes
#setwd(dirname(rstudioapi::getSourceEditorContext()$path))
source("./functions.R")
load('./../raw_data.rdata')

# get quotes
quote_dt <- modeling_data

# get attrition
data_parsed_dt <- parse_comment(data)
attrit_dt <- get_attrition(data_parsed_dt)
quote_plus_attrit_dt <- rbind(get_quote_records(data_parsed_dt), attrit_dt)
```

```{r, echo=FALSE}
# utility functions
get_robust_se <- function(mod){
  # ACCEPTS linear model
  # appends robust error
  # RETURNS linear model
  
  mod$vcovHC_ <- vcovHC(mod)
  return(sqrt(diag(mod$vcovHC_)))
  
  #return (mod)
}
```


```{r, echo=FALSE}
# morning_call
quote_dt[, morning_call := ifelse(time <=12, 1, 0)]

# price_range
quote_dt[, price_range := ifelse(is.na(quote_range_low), 0, 1)]

# update the attrition as raw data has the wrong label
quote_plus_attrit_dt[, attrition := 0]
quote_plus_attrit_dt[
            (no_quote_reason == 'refused_to_provide_quote') |
            (no_quote_reason == 'failed_callback') |
            (no_quote_reason == 'unable_to_provide_quote'), attrition := 1]
```



```{r, echo=FALSE}
# gender
model_g <- lm(outcome ~ treat + as.factor(county) + chain, data=quote_dt)
# gender + race
model_gr <- lm(outcome ~ treat + esl_caller + treat:esl_caller + as.factor(county) + chain, data=quote_dt)
# gender + race + affinity
model_gr_af <- lm(outcome ~ treat + esl_caller + treat:esl_caller + gender_affinity + esl_affinity + as.factor(county) + chain, data=quote_dt)

# print stargazer
model_list = list(
    model_g,
    model_gr,
    model_gr_af
)
se_list = list(
    coeftest(model_g, vcov=vcovHC(model_g, type="HC"))[ , "Std. Error"],
    coeftest(model_gr, vcov=vcovHC(model_gr, type="HC"))[ , "Std. Error"],
    coeftest(model_gr_af, vcov=vcovHC(model_gr_af, type="HC"))[ , "Std. Error"]
)
#stargazer(model_list, se=se_list, align=TRUE, type='text')
```

## EBA for Model 1: Treatment Effect  

```{r,echo=FALSE, warning=FALSE, message=FALSE}

# get all entries attrit or withquote
attrit_and_quote_data <- data[!is.na(outcome)|attrition ==1, .(outcome,treat, esl_caller, gender_affinity, esl_affinity, county, chain)]


# fill in low bounds
outcome_min_value <- attrit_and_quote_data[ , min(outcome, na.rm = TRUE)]

attrit_and_quote_data[ , outcome_min := outcome]
attrit_and_quote_data[is.na(outcome_min), outcome_min := outcome_min_value]

# 25%
outcome_25_value <- attrit_and_quote_data[ , quantile(outcome, probs = 0.25, na.rm = TRUE)]

attrit_and_quote_data[ , outcome_25 := outcome]
attrit_and_quote_data[is.na(outcome_25), outcome_25 := outcome_25_value]

# 75%
outcome_75_value <- attrit_and_quote_data[ , quantile(outcome, probs = 0.5, na.rm = TRUE)]

attrit_and_quote_data[ , outcome_75 := outcome]
attrit_and_quote_data[is.na(outcome_75), outcome_75 := outcome_75_value]

#fill in with high values}
outcome_high_value <- attrit_and_quote_data[ , max(outcome, na.rm = TRUE)]

attrit_and_quote_data[ , outcome_max := outcome]
attrit_and_quote_data[is.na(outcome_max), outcome_max := outcome_high_value]

model <- lm(outcome ~ treat, data=quote_dt)

model_low <- attrit_and_quote_data[ , lm(outcome_min ~ treat)]
model_25 <- attrit_and_quote_data[ , lm(outcome_25 ~ treat)]
model_75 <- attrit_and_quote_data[ , lm(outcome_75 ~ treat)]
model_high <- attrit_and_quote_data[ , lm(outcome_max ~ treat)]

# stargazer
stargazer(
  model, 
  model_low, 
  model_25, 
  model_75, 
  model_high,
  type = 'text', 
  se = list(
    get_robust_se(model),
    get_robust_se(model_low), 
    get_robust_se(model_25),
    get_robust_se(model_75),
    get_robust_se(model_high) ), 
  add.lines = list(
            c('SE Flavor','Robust', 'Robust', 'Robust', 'Robust', 'Robust'),
            c('County-Chain fixed effects', 'No', 'No', 'No', 'No','No')
            )
  #, omit = c('county', 'chain')
          #omit.labels = "County and Chain Fixed Effects"
  ,no.space = TRUE, 
  column.sep.width = "3pt", 
  font.size = "small" 
  )

```

\newpage

## EBA for Model 2: Fixed Effects

```{r, echo=FALSE,warning=FALSE, message=FALSE}
model_low <- attrit_and_quote_data[ , lm(outcome_min ~ treat + as.factor(county) + chain)]
model_25 <- attrit_and_quote_data[ , lm(outcome_25 ~ treat + as.factor(county) + chain)]
model_75 <- attrit_and_quote_data[ , lm(outcome_75 ~ treat + as.factor(county) + chain)]
model_high <- attrit_and_quote_data[ , lm(outcome_max ~ treat + as.factor(county) + chain)]

# stargazer
stargazer(
  model_g, 
  model_low, 
  model_25, 
  model_75, 
  model_high,
  type = 'text', 
  se = list(
    get_robust_se(model_g),
    get_robust_se(model_low), 
    get_robust_se(model_25),
    get_robust_se(model_75),
    get_robust_se(model_high) ), 
  add.lines = list(
            c('SE Flavor','Robust', 'Robust', 'Robust', 'Robust', 'Robust'),
            c('County-Chain fixed effects', 'Yes', 'Yes', 'Yes', 'Yes','Yes')
            ),
  omit = c('county', 'chain')
          #omit.labels = "County and Chain Fixed Effects"
  ,no.space = TRUE, 
  column.sep.width = "3pt", 
  font.size = "small" 
  )
```


\newpage
## EBA for Model 3: Heterogenous Treatment Effects


```{r, echo=FALSE,warning=FALSE, message=FALSE}

model_low <- attrit_and_quote_data[ , lm(outcome_min ~ treat + esl_caller + treat:esl_caller + as.factor(county) + chain)]

model_25 <- attrit_and_quote_data[ , lm(outcome_25 ~ treat + esl_caller + treat:esl_caller + as.factor(county) + chain)]

model_75 <- attrit_and_quote_data[ , lm(outcome_75 ~ treat + esl_caller + treat:esl_caller + as.factor(county) + chain)]

model_high <- attrit_and_quote_data[ , lm(outcome_max ~ treat + esl_caller + treat:esl_caller + as.factor(county) + chain)]

# stargazer
stargazer(
  model_gr, 
  model_low, 
  model_25, 
  model_75, 
  model_high,
  type = 'text', 
  se = list(
    get_robust_se(model_g),
    get_robust_se(model_low), 
    get_robust_se(model_25),
    get_robust_se(model_75),
    get_robust_se(model_high) ), 
  add.lines = list(
            c('SE Flavor','Robust', 'Robust', 'Robust', 'Robust', 'Robust'),
            c('County-Chain fixed effects', 'Yes', 'Yes', 'Yes', 'Yes','Yes')
            ),
  omit = c('county', 'chain')
          #omit.labels = "County and Chain Fixed Effects"
  ,no.space = TRUE, 
  column.sep.width = "3pt", 
  font.size = "small" 
  )
```


\newpage
## EBA for Model 4: Interaction Effects


```{r, echo=FALSE,warning=FALSE, message=FALSE}

model_low <- attrit_and_quote_data[ , lm(outcome_min ~ treat + esl_caller + gender_affinity + esl_affinity + 
                                treat:esl_caller + treat:esl_affinity + treat:gender_affinity + 
                                as.factor(county) + chain)]


model_25 <- attrit_and_quote_data[ , lm(outcome_25 ~ treat + esl_caller + gender_affinity + esl_affinity + 
                                treat:esl_caller + treat:esl_affinity + treat:gender_affinity + 
                                as.factor(county) + chain)]

model_75 <- attrit_and_quote_data[ , lm(outcome_75 ~ treat + esl_caller + gender_affinity + esl_affinity + 
                                treat:esl_caller + treat:esl_affinity + treat:gender_affinity + 
                                as.factor(county) + chain)]

model_high <- attrit_and_quote_data[ , lm(outcome_max ~ treat + esl_caller + gender_affinity + esl_affinity + 
                                treat:esl_caller + treat:esl_affinity + treat:gender_affinity + 
                                as.factor(county) + chain)]

# stargazer
stargazer(
  model_gr_af, 
  model_low, 
  model_25, 
  model_75, 
  model_high,
  type = 'text', 
  se = list(
    get_robust_se(model_gr_af),
    get_robust_se(model_low), 
    get_robust_se(model_25),
    get_robust_se(model_75),
    get_robust_se(model_high) ), 
  add.lines = list(
            c('SE Flavor','Robust', 'Robust', 'Robust', 'Robust', 'Robust'),
            c('County-Chain fixed effects', 'Yes', 'Yes', 'Yes', 'Yes','Yes')
            ),
  omit = c('county', 'chain')
          #omit.labels = "County and Chain Fixed Effects"
  ,no.space = TRUE, 
  column.sep.width = "3pt", 
  font.size = "small" 
  )
```

\end{landscape}